{"name": "test_case03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_case_01.TestCaseClass object at 0x00000232C121B208>\n\n    def test_case03(self):\n        print('执行用例03......')\n>       assert 0  # 断言失败\nE       assert 0\n\ntest_case_01.py:23: AssertionError"}, "start": 1588051809664, "stop": 1588051809664, "uuid": "b673cb94-f34d-4b0d-983d-bcc662ab9f99", "historyId": "e465731ea534fece753a274c7adee096", "testCaseId": "2bdf5a3ced455d00ca2eb3cfbb45a1b5", "fullName": "test_case_01.TestCaseClass#test_case03", "labels": [{"name": "suite", "value": "test_case_01"}, {"name": "subSuite", "value": "TestCaseClass"}, {"name": "host", "value": "PC-BFD8TY2"}, {"name": "thread", "value": "1676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_01"}]}