{"name": "test_case03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_case_01.TestCaseClass object at 0x000001A370967588>\n\n    def test_case03(self):\n        print('执行用例03......')\n>       assert 0  # 断言失败\nE       assert 0\n\ntest_case_01.py:23: AssertionError"}, "start": 1604310725701, "stop": 1604310725701, "uuid": "a600e9a8-9453-4917-af65-e5c1ead84634", "historyId": "e465731ea534fece753a274c7adee096", "testCaseId": "2bdf5a3ced455d00ca2eb3cfbb45a1b5", "fullName": "test_case_01.TestCaseClass#test_case03", "labels": [{"name": "suite", "value": "test_case_01"}, {"name": "subSuite", "value": "TestCaseClass"}, {"name": "host", "value": "DESKTOP-6Q15HJ3"}, {"name": "thread", "value": "161496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_01"}]}